name: Terraform Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "terraform/**"
      - "app.py"
      - "requirements.txt"

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION || 'eu-north-1' }}

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform plan
        env:
          TF_VAR_ssh_cidr: ${{ secrets.TF_VAR_ssh_cidr }}
          TF_VAR_key_name: ${{ vars.TF_VAR_key_name || 'test' }}
          TF_VAR_enable_ssh: ${{ vars.TF_VAR_enable_ssh || 'false' }}
          TF_VAR_enable_alb: ${{ vars.TF_VAR_enable_alb || 'true' }}
          TF_VAR_enable_https: ${{ vars.TF_VAR_enable_https || 'false' }}
          TF_VAR_environment: ${{ vars.TF_VAR_environment || 'dev' }}
          TF_VAR_github_owner: ${{ vars.GITHUB_OWNER || '' }}
          TF_VAR_github_repo: ${{ vars.GITHUB_REPO || github.event.repository.name }}
          TF_VAR_alarm_email: ${{ vars.ALARM_EMAIL || '' }}
        run: terraform plan -no-color -input=false

  apply:
    name: Terraform apply
    needs: plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION || 'eu-north-1' }}

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform apply
        env:
          TF_VAR_ssh_cidr: ${{ secrets.TF_VAR_ssh_cidr }}
          TF_VAR_key_name: ${{ vars.TF_VAR_key_name || 'test' }}
          TF_VAR_enable_ssh: ${{ vars.TF_VAR_enable_ssh || 'false' }}
          TF_VAR_enable_alb: ${{ vars.TF_VAR_enable_alb || 'true' }}
          TF_VAR_enable_https: ${{ vars.TF_VAR_enable_https || 'false' }}
          TF_VAR_environment: ${{ vars.TF_VAR_environment || 'dev' }}
          TF_VAR_github_owner: ${{ vars.GITHUB_OWNER || '' }}
          TF_VAR_github_repo: ${{ vars.GITHUB_REPO || github.event.repository.name }}
          TF_VAR_alarm_email: ${{ vars.ALARM_EMAIL || '' }}
        run: terraform apply -auto-approve -input=false
